-- AlterTable
ALTER TABLE "Movie" ADD COLUMN "ageRating" TEXT;
ALTER TABLE "Movie" ADD COLUMN "genres" TEXT;
ALTER TABLE "Movie" ADD COLUMN "language" TEXT;
ALTER TABLE "Movie" ADD COLUMN "profit" REAL;
ALTER TABLE "Movie" ADD COLUMN "rating" INTEGER DEFAULT 0;
ALTER TABLE "Movie" ADD COLUMN "revenue" REAL;
ALTER TABLE "Movie" ADD COLUMN "status" TEXT;
ALTER TABLE "Movie" ADD COLUMN "voteCount" INTEGER DEFAULT 0;
